main: me.saltyfishhy.throwTNT.Main
name: throwableTNT
author: saltyfishhy
version: 1.1.0

commands:
  tnttutorial:
    description: Tells a user how to use the plugin
  gettnt:
    description: Gives a user either 1 piece of throwing tnt or the specified amount
  tntreload:
    description: Lets a user with the permission "tnt.admin" reload the config
